
/*** GENERATED BY stabbity.pl ***/
#ifndef IG_PGM_STRING_TABLE_H
#define IG_PGM_STRING_TABLE_H

#include <avr/pgmspace.h>

#define STABX_ITEM(item,content) prog_char STAB_##item [] PROGMEM = content
STABX_ITEM(invalid, "INVALID STAB ENTRY AAARGGHH");
STABX_ITEM(hello_1, "hello");
STABX_ITEM(hello_2, "hello world");
STABX_ITEM(diaf, "die in a fire");
STABX_ITEM(hexdigits, "0123456789ABCDEF");

#define STABX_LONGEST_SIZE 27

#define INVALID 0
#define HELLO_1 1
#define HELLO_2 2
#define DIAF 3
#define HEXDIGITS 4

#define STABX_LAST_ITEM_INDEX 4

PROGMEM const char* STABX_table[] = {
	STAB_invalid,
	STAB_hello_1,
	STAB_hello_2,
	STAB_diaf,
	STAB_hexdigits,
};


char STABX_buffer[STABX_LONGEST_SIZE+1];

#define STABX_GET(x) strncpy_P(STABX_buffer,(char*)pgm_read_word(&(STABX_table[x > STABX_LAST_ITEM_INDEX ? 0 : x])),STABX_LONGEST_SIZE)

#endif /* IG_PGM_STRING_TABLE_H */
